source ~/.quantumrc
export EDITOR=nvim
export PAGER='bat --theme ansi'

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# zsh options
setopt prompt_subst
setopt appendhistory            # save to histfile
setopt share_history            # save on each command
setopt extended_history         # save timestamp with history
setopt hist_ignore_dups         # don't store duplicate commands

# some env vars
export MANROFFOPT='-c'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
#export PATH="$PATH:/home/jeffrey/.local/share/coursier/bin"
export PATH="$PATH:'/usr/local/go/bin:$HOME/.local/bin"
export WORKSPACE="$HOME/workspace"

# setup fzf
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git' 
export FZF_CTRL_T_COMMAND='fd --type f --hidden --exclude .git' 
export FZF_ALT_C_COMMAND='fd --type d' 
source <(fzf --zsh)

# prompt setup
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )

PROMPT='%3~ %# '
RPROMPT='${vcs_info_msg_0_}'

# aliases
alias ls='lsd'
alias ll='ls -al'
alias la='ls -a'
alias lr='ls -ltr'
alias lg='ls -l --git'

alias n='nvim'
alias nq='nvim-qt'
alias xo='xdg-open'

alias gp='git pull'
alias gs='git st'
alias gl='git lg'

alias bat='bat --theme ansi'
alias k='kubectl'

# DR specific stuff
function globalprotect_restart() {
    /opt/paloaltonetworks/globalprotect-service-restart.sh
    /opt/paloaltonetworks/globalprotect/globalprotect launch-ui --recover
}

function dr_start() {
    ./start.sh --quick --no-smoke --credentials $@
}

function dr() {
    cd ~/workspace/DataRobot/
    workon dev
    source etc/profile
}

function rm_unknown() {
    git ls-files --others --exclude-standard -z | xargs -0 -n 1 rm
}

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/home/jeffrey/google-cloud-sdk/path.zsh.inc' ]; then . '/home/jeffrey/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '/home/jeffrey/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/jeffrey/google-cloud-sdk/completion.zsh.inc'; fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="$HOME/.sdkman"
#[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# all the completions scripts are saved to ~/.zfunc
fpath+=~/.zfunc
autoload -Uz compinit && compinit

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

zstyle ':completion:*' menu select
